format = """
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$python\
$character
"""
right_format = "$time"

[aws]
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) " 
read_only = " 󰌾 "
read_only_style = "red"
style = "bold bright-blue"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
format = "[$symbol](green) [$branch]($style) "
style = "blue"
truncation_length = 50
symbol = ""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
style = "italic bright-blue"
format = """([$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style))"""
conflicted = "[≠](italic bright-magenta) "
ahead = "[⇡ ${count}](italic blue) "
behind = "[⇣ ${count}](italic red) "
diverged = "[⇕ ⇡ [${ahead_count}](regular white) ⇣ [${behind_count}](white)](bright-magenta) "
untracked = "[?$count](bright-yellow) "
stashed = "[󰏢](bright-green) "
modified = "[~$count](yellow) "
staged = "[+$count](bright-cyan) "
renamed = "[»](bright-blue) "
deleted = "[-$count](italic red) "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[line_break]
disabled = false
add_newline = false 

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os]
format = "[$symbol]($style)"
style = "purple"
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[time]
format = "[$time]($style)"
time_format = "%r %b %d"
style = "bold bright-black"
disabled = false

[username]
show_always = true
format = '[$user ]($style)'
disabled = false

[zig]
symbol = " "
